#!/usr/bin/env python3
"""Generate every app icon from the token block.

CLAUDE.md promises that swapping the palette is one edit to :root in
src/styles/tokens.css. Icons are the place that promise quietly breaks: they are
baked pixels, they live in six directories, and nothing type-checks them. So
they are generated rather than drawn, and the colours are read from tokens.css
at generation time.

    python3 scripts/make-icons.py

Writes: public/favicon.svg, public/icon-{192,512}.png, and the Android launcher
set under android/app/src/main/res/ (legacy, round and adaptive-foreground at
every density) plus the adaptive background colour.

The mark is "IN" — a paper bar and an accent N on an ink ground. It predates the
rename to MovingOut and still reads as Independencia, which is the design's name
and the thing the app is actually about.
"""

import re
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "src" / "styles" / "tokens.css"

# Supersample factor. The mark is all round caps and a rounded ground, and
# Pillow has no antialiasing of its own — drawing big and shrinking is the whole
# antialiasing strategy.
SS = 8

# The mark is authored in a 64-unit square, matching public/favicon.svg.
UNIT = 64


def tokens() -> dict[str, str]:
    """--name: #hex pairs from the :root block."""
    css = TOKENS.read_text(encoding="utf-8")
    return dict(re.findall(r"(--[\w-]+):\s*(#[0-9a-fA-F]{3,8})", css))


def palette() -> tuple[str, str, str]:
    t = tokens()
    # --accent-l, not --accent: tokens.css labels it "the accent, legible on
    # ink", and indigo #4438CA on near-black ink is a smudge at 48 px.
    return t["--ink"], t["--bg"], t["--accent-l"]


def draw_mark(size: int, *, ground: bool, inset: float = 1.0, round_ground: bool = False) -> Image.Image:
    """The IN mark at `size` px.

    ground=False leaves it transparent, for the adaptive-icon foreground layer.
    inset scales the artwork within the canvas — Android's adaptive icons crop
    to an inner circle, so the foreground has to sit inside a safe zone.
    """
    ink, paper, accent = palette()
    px = size * SS
    img = Image.new("RGBA", (px, px), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    if ground:
        if round_ground:
            d.ellipse([0, 0, px - 1, px - 1], fill=ink)
        else:
            d.rounded_rectangle([0, 0, px - 1, px - 1], radius=14 / UNIT * px, fill=ink)

    # Map 64-unit coordinates onto the (possibly inset) canvas.
    span = px * inset
    origin = (px - span) / 2

    def u(v: float) -> float:
        return origin + v / UNIT * span

    # The I: a paper bar.
    d.rounded_rectangle([u(14), u(14), u(21), u(50)], radius=2 / UNIT * span, fill=paper)

    # The N: one polyline, round joins, round caps drawn on as discs.
    stroke = 7 / UNIT * span
    pts = [(u(29), u(50)), (u(29), u(14)), (u(45), u(36)), (u(45), u(14))]
    d.line(pts, fill=accent, width=int(round(stroke)), joint="curve")
    r = stroke / 2
    for x, y in (pts[0], pts[-1]):
        d.ellipse([x - r, y - r, x + r, y + r], fill=accent)

    return img.resize((size, size), Image.LANCZOS)


def write(img: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, "PNG")
    print(f"  {path.relative_to(ROOT)}")


def main() -> None:
    ink, paper, accent = palette()
    print(f"palette: ink={ink} paper={paper} accent={accent}")

    print("web / PWA:")
    for size in (192, 512):
        write(draw_mark(size, ground=True), ROOT / "public" / f"icon-{size}.png")

    favicon = ROOT / "public" / "favicon.svg"
    favicon.write_text(
        f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="MovingOut">
  <!-- Generated by scripts/make-icons.py from the tokens.css :root block. -->
  <rect width="64" height="64" rx="14" fill="{ink}"/>
  <rect x="14" y="14" width="7" height="36" rx="2" fill="{paper}"/>
  <path d="M29 50V14l16 22V14" fill="none" stroke="{accent}" stroke-width="7"
        stroke-linecap="round" stroke-linejoin="round"/>
</svg>
""",
        encoding="utf-8",
    )
    print(f"  {favicon.relative_to(ROOT)}")

    res = ROOT / "android" / "app" / "src" / "main" / "res"
    if not res.exists():
        print("no android/ project — skipping launcher icons")
        return

    # Legacy launcher is 48dp; adaptive layers are 108dp with only the middle
    # 72dp guaranteed visible and 66dp genuinely safe. 66/108 is that safe zone.
    densities = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
    print("android launcher:")
    for name, scale in densities.items():
        out = res / f"mipmap-{name}"
        write(draw_mark(int(48 * scale), ground=True), out / "ic_launcher.png")
        write(draw_mark(int(48 * scale), ground=True, round_ground=True), out / "ic_launcher_round.png")
        write(draw_mark(int(108 * scale), ground=False, inset=66 / 108), out / "ic_launcher_foreground.png")

    bg = res / "values" / "ic_launcher_background.xml"
    bg.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<resources>\n"
        f'    <color name="ic_launcher_background">{ink}</color>\n'
        "</resources>\n",
        encoding="utf-8",
    )
    print(f"  {bg.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
